name: Deployment Example

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Specify your environment here
    steps:
      - name: Get Deployment Context
        run: |
          echo "Deploying to environment: ${{ toJson(github) }}"
          echo "Job name: ${{ job.deploy.environment }}"
